-- ============================================================
-- SEED: Real Homer Gere Content
-- Replaces fictional seed data with actual verified content
-- ============================================================

-- Delete fictional seed data from migration 014
DELETE FROM filmography_entries;
DELETE FROM journey_entries;
DELETE FROM experiences;
DELETE FROM experience_requests;
DELETE FROM journal_articles;
DELETE FROM media_videos;
DELETE FROM media_podcasts;
DELETE FROM media_press;

-- ============================================================
-- MEMBERSHIP PLANS (update existing)
-- ============================================================

UPDATE membership_plans SET name = 'Silver', slug = 'silver', description = 'Perfect for fans who want to stay connected with Homer''s career and receive exclusive updates.', price = 19.00, badge = NULL, is_popular = false, features = ARRAY['Exclusive Updates & Newsletter', 'Members-Only Behind-the-Scenes', 'Early Access to Project News', 'Private Discord Community Access']::text[], cta_text = 'Join Silver', availability = 'available', requires_approval = false WHERE slug = 'supporter';

UPDATE membership_plans SET name = 'Gold', slug = 'gold', description = 'The most popular tier for dedicated fans seeking priority access and exclusive content.', price = 49.00, badge = 'MOST POPULAR', is_popular = true, features = ARRAY['Exclusive Updates & Newsletter', 'Members-Only Behind-the-Scenes', 'Early Access to Project News', 'Private Discord Community Access', 'Behind-the-Scenes Video Vlogs', 'Priority Access to Experiences', 'Members-Only Monthly Giveaways']::text[], cta_text = 'Join Gold', availability = 'available', requires_approval = false WHERE slug = 'inner-circle';

UPDATE membership_plans SET name = 'Platinum', slug = 'platinum', description = 'The ultimate membership for the most dedicated fans with full VIP access and personal perks.', price = 99.00, badge = NULL, is_popular = false, features = ARRAY['Exclusive Updates & Newsletter', 'Members-Only Behind-the-Scenes', 'Early Access to Project News', 'Private Discord Community Access', 'Behind-the-Scenes Video Vlogs', 'Priority Access to Experiences', 'Members-Only Monthly Giveaways', 'VIP Film Event Invitations', 'Personalized Video Shoutout Annually']::text[], cta_text = 'Join Platinum', availability = 'available', requires_approval = true WHERE slug = 'vip-access';

-- ============================================================
-- JOURNEY ENTRIES
-- ============================================================

INSERT INTO journey_entries (year, title, description, details, icon_name, highlight, sort_order) VALUES
(2000, 'Born in New York', 'Born Homer James Jigme Gere on February 6, 2000 in New York City.', 'Named after his paternal grandfather Homer George Gere. His middle name "Jigme" is Tibetan for "fearless" or "courageous," reflecting his father''s Buddhist faith.', 'user', NULL, 1),
(2018, 'Graduated Hackley School', 'Completed secondary education at Hackley School in Westchester, New York.', 'Attended the private Hackley School from September 2014 through graduation in June 2018.', 'graduation-cap', NULL, 2),
(2019, 'Brown University', 'Enrolled at Brown University to study Cognitive Neuroscience and Visual Arts.', 'Joined Brown University in Providence, Rhode Island, pursuing a Bachelor of Arts degree majoring in Cognitive Neuroscience and Visual Arts. Graduated in 2024.', 'graduation-cap', NULL, 3),
(2023, 'Early Film Work', 'Appeared in short film projects before transitioning to major television roles.', 'Built early experience through independent short film projects, including credits on IMDB for short films prior to his television debut.', 'clapperboard', NULL, 4),
(2026, 'Euphoria Season 3', 'Cast as Dylan Reid in HBO''s Euphoria third and final season.', 'Made his television debut portraying Dylan Reid in 4 episodes. The casting was announced by BBC News in October 2025; the season premiered in May 2026.', 'award', 'TV Debut', 5),
(2025, 'The Shards', 'Cast as Robert Mallory in Ryan Murphy and Bret Easton Ellis''s FX/Hulu series.', 'His first major leading role, starring alongside Igby Rigney, Kaia Gerber, Hayes Warner, Graham Campbell, Wes Bentley, and Evan Rachel Wood. Premiered August 5, 2026.', 'star', 'First Lead Role', 6),
(2026, 'White Lies', 'Cast in an Oliver Stone film.', 'Announced in June 2026, Gere was cast in the Oliver Stone film "White Lies." Details about the role and release date are forthcoming.', 'film', NULL, 7);

-- ============================================================
-- JOURNAL ARTICLES
-- ============================================================

INSERT INTO journal_articles (slug, title, excerpt, content, category, author, author_role, cover_image, published_date, reading_time, word_count, featured, trending, status, tags, seo_title, seo_description) VALUES
('the-shards-world-premiere-sva-theatre', 'The Shards Makes Its World Debut at SVA Theatre', 'Homer Gere leads the cast of FX''s The Shards at the world premiere in New York City.', 'On the evening of July 27, 2026, the cast and creative team of FX''s The Shards descended upon the SVA Theatre in Manhattan''s Chelsea neighborhood for the world premiere of the series. Homer Gere, who stars as Robert Mallory in what is his first leading role in a major television production, walked the red carpet alongside his co-stars Kaia Gerber, Igby Rigney, Graham Campbell, and Hayes Warner.', 'events', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-08-08', '12 min read', 1847, true, true, 'published', ARRAY['The Shards', 'Premiere', 'FX', 'Ryan Murphy', 'Robert Mallory']::text[], 'The Shards World Premiere at SVA Theatre — Homer Gere Leads FX Series', 'Full coverage of the world premiere of FXs The Shards at SVA Theatre in New York City.'),

('euphoria-season-3-hbo-premiere', 'Euphoria Season 3 Premieres on HBO', 'Homer Gere returns as Dylan Reid across four episodes of the new season.', 'HBO''s Euphoria Season 3 premiered on May 21, 2026, marking the return of one of the network''s most culturally significant series. Homer Gere reprises his role as Dylan Reid, appearing in four episodes of the ten-episode season.', 'productions', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-05-22', '11 min read', 1634, false, true, 'published', ARRAY['Euphoria', 'HBO', 'Season 3', 'Dylan Reid']::text[], 'Euphoria Season 3 — Homer Gere as Dylan Reid | HBO', 'Homer Gere returns as Dylan Reid in Euphoria Season 3 on HBO.'),

('oliver-stone-white-lies-film-announcement', 'Oliver Stone''s White Lies Confirms Homer Gere Alongside Douglas, Dafoe', 'Academy Award-winning director Oliver Stone assembles a formidable cast including Homer Gere.', 'In June 2026, it was announced that Homer Gere has been cast in Oliver Stone''s upcoming feature film White Lies, alongside Academy Award winners Michael Douglas, Willem Dafoe, and Ellen Barkin.', 'announcements', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-06-15', '10 min read', 1589, false, true, 'published', ARRAY['White Lies', 'Oliver Stone', 'Michael Douglas', 'Willem Dafoe']::text[], 'Oliver Stone''s White Lies — Homer Gere Cast Alongside Douglas & Dafoe', 'Homer Gere joins Oliver Stone''s White Lies alongside Michael Douglas, Willem Dafoe, and Ellen Barkin.'),

('british-vogue-who-is-homer-gere', 'Who Is Homer Gere? — British Vogue Explores the Next Chapter', 'British Vogue publishes a comprehensive profile on Homer Gere ahead of The Shards premiere.', 'In the weeks leading up to the premiere of The Shards, British Vogue published a comprehensive profile on Homer Gere under the headline "Who Is Homer Gere?" — a question that, at the time, many in the entertainment industry were beginning to ask with increasing urgency.', 'press', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-07-20', '9 min read', 1420, false, false, 'published', ARRAY['British Vogue', 'Profile', 'The Shards']::text[], '"Who Is Homer Gere?" — British Vogue Profile', 'British Vogue publishes a comprehensive profile on Homer Gere.'),

('the-shards-behind-the-scenes-65mm-film', 'Behind the Lens: How The Shards Was Shot on 65mm Film', 'An inside look at the cinematography choices behind FX''s most visually ambitious series.', 'The decision to shoot The Shards on 65mm Kodak VERITA 200D film stock was driven by the desire to capture an immersive visual quality that digital formats cannot replicate. Cinematographer Marcell Rév brought his distinctive visual approach to the series.', 'behind-the-scenes', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-08-12', '8 min read', 1200, false, false, 'published', ARRAY['The Shards', 'Cinematography', '65mm', 'Marcell Rév', 'Behind the Scenes']::text[], 'Behind the Lens: How The Shards Was Shot on 65mm Film', 'An inside look at the cinematography behind FX The Shards.'),

('the-shards-launch-party-moonlight-rollerway', 'The Shards Cast Gathers at Moonlight Rollerway', 'The official launch party for FX''s The Shards brings the cast together for a night of celebration.', 'Following the world premiere at SVA Theatre, the cast and crew of The Shards gathered at Moonlight Rollerway in Glendale, California for the official series launch party.', 'events', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-08-06', '6 min read', 900, false, false, 'published', ARRAY['The Shards', 'Launch Party', 'Moonlight Rollerway']::text[], 'The Shards Launch Party at Moonlight Rollerway', 'The official launch party for FX The Shards.'),

('brown-university-cognitive-neuroscience-visual-arts', 'From Brown University to the Screen', 'How Homer Gere''s education in cognitive neuroscience shaped his approach to acting.', 'Studying Cognitive Neuroscience and Visual Arts at Brown University gave Homer Gere a unique lens on performance. Understanding how the brain processes emotion and perception has directly influenced how he approaches character work.', 'personal-stories', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-04-10', '7 min read', 1100, false, false, 'published', ARRAY['Brown University', 'Education', 'Cognitive Neuroscience']::text[], 'From Brown University to the Screen — Homer Gere', 'How Homer Gere education shaped his approach to acting.'),

('bbc-news-highlights-homer-gere', 'BBC News Highlights Homer Gere as Emerging Talent', 'BBC News features Homer Gere in a roundup of emerging talent to watch in 2026.', 'BBC News featured Homer Gere in a roundup of emerging talent to watch in 2026, highlighting his background, education, and rapidly growing career in the entertainment industry.', 'press', 'Official Editorial', 'HomerGere.com Editorial Team', NULL, '2026-03-15', '5 min read', 800, false, false, 'published', ARRAY['BBC News', 'Emerging Talent']::text[], 'BBC News Highlights Homer Gere as Emerging Talent', 'BBC News features Homer Gere in emerging talent roundup.');

-- ============================================================
-- FILMOGRAPHY
-- ============================================================

INSERT INTO filmography_entries (title, role, year, status, description, type, image_url, sort_order) VALUES
('White Lies', 'TBA', 2027, 'In Production', 'An Oliver Stone film starring alongside Michael Douglas, Willem Dafoe, and Ellen Barkin.', 'film', NULL, 1),
('The Shards', 'Robert Mallory (Lead)', 2026, 'Released', 'A Ryan Murphy and Bret Easton Ellis adaptation for FX/Hulu. Homer''s first lead role, starring alongside Kaia Gerber and Igby Rigney.', 'series', NULL, 2),
('Euphoria', 'Dylan Reid', 2026, 'Released', 'HBO''s Euphoria Season 3. Homer appears in 4 episodes as Dylan Reid.', 'series', NULL, 3),
('American Pledge', 'Lead', 2024, 'Released', 'Short film project.', 'short', NULL, 4);

-- ============================================================
-- EXPERIENCES
-- ============================================================

INSERT INTO experiences (title, description, type, category, price, image_url, availability, duration, location, whats_included, eligibility, important_notes, sort_order) VALUES
('Meet & Greet', 'An exclusive in-person meeting with Homer at a private event or premiere.', 'meet-and-greet', 'meet-and-greet', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2025/07/kaia-gerber-homer-gere-the-shards-300x450.jpg', 'available', '15–30 minutes', 'Event-dependent (major cities)', ARRAY['Personal introduction and meet & greet', 'Professional photo opportunity', 'Personalized signed memorabilia', 'Exclusive event access']::text[], ARRAY['Must be 18 years or older', 'Valid government-issued ID required', 'Subject to background verification']::text[], ARRAY['All requests are reviewed by management', 'Availability is not guaranteed', 'Travel arrangements may be required']::text[], 1),
('Fan Event', 'Attend a curated fan event featuring Homer as the special guest.', 'fan-event', 'fan-event', 'Request Pricing', 'https://assets.vogue.com/photos/6a692e094e8db1ed5e9e4dff/16:9/w_1280,c_limit/FX_Shards_SA_285.JPG', 'limited', '2–3 hours', 'Various venues', ARRAY['Reserved seating at the event', 'Q&A session with Homer', 'Meet & greet opportunity', 'Exclusive event merchandise']::text[], ARRAY['Must be 16 years or older', 'Ticket purchase required', 'Limited capacity per event']::text[], ARRAY['Events are scheduled periodically', 'Capacity is strictly limited', 'No recording permitted during the event']::text[], 2),
('Charity Appearance', 'Request Homer''s presence at a charity event or fundraiser.', 'charity-appearance', 'charity-auction', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2026/07/GettyImages-2287310934-scaled.jpg', 'available', '1–4 hours', 'Event-dependent', ARRAY['Appearance at the charity event', 'Speaking or presentation', 'Photo opportunities with attendees', 'Social media coverage']::text[], ARRAY['Must be a registered nonprofit or charity', 'Event must align with approved causes', 'Minimum 30-day advance request']::text[], ARRAY['Charity events receive priority consideration', 'Travel and accommodation may be provided by the organization', 'Management reserves final approval']::text[], 3),
('Speaking Engagement', 'Invite Homer to speak at conferences, panels, or educational events.', 'speaking-engagement', 'business', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2026/08/homer-gere-the-shards.jpg', 'available', '1–2 hours', 'Event-dependent (virtual or in-person)', ARRAY['Keynote or panel appearance', 'Pre-event consultation on topics', 'Q&A session with audience', 'Meet & greet after the event']::text[], ARRAY['Must be a recognized institution or organization', 'Event must be professional in nature', 'Minimum 45-day advance request']::text[], ARRAY['Speaking topics must be pre-approved', 'Travel and accommodation required for in-person events', 'Virtual appearances available for select events']::text[], 4),
('Brand Collaboration', 'Partner with Homer for endorsement, campaign, or creative projects.', 'brand-collaboration', 'business', 'Custom Pricing', 'https://assets.vogue.com/photos/6a70cdc2c9944acffc837ccf/16:9/w_1280,c_limit/VO0926_Cover_logo.jpg', 'available', 'Project-dependent', 'Flexible', ARRAY['Brand endorsement or campaign participation', 'Social media amplification', 'Event or launch appearance', 'Creative consultation']::text[], ARRAY['Must be a registered business or brand', 'Brand must align with Homers values', 'Minimum 60-day advance request']::text[], ARRAY['All partnerships require management approval', 'Exclusivity terms may apply', 'Usage rights and contracts are negotiated separately']::text[], 5),
('Private Event', 'Book Homer for a private celebration, corporate event, or intimate gathering.', 'private-event', 'business', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2025/10/the-shards-cast.jpg', 'limited', '2–4 hours', 'Host-arranged venue', ARRAY['Personalized attendance at the event', 'Meet & greet with host and guests', 'Photo opportunities', 'Signed memorabilia for the host']::text[], ARRAY['Must be 21 years or older', 'Event must meet venue and safety requirements', 'Minimum 60-day advance request']::text[], ARRAY['Private events require extensive vetting', 'Travel and security arrangements are the hosts responsibility', 'Subject to schedule availability']::text[], 6),
('Virtual Appearance', 'A live video call experience with Homer from anywhere in the world.', 'virtual-appearance', 'virtual-session', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2026/06/GettyImages-2152915757-scaled.jpg', 'available', '15–30 minutes', 'Virtual (worldwide)', ARRAY['Live 1-on-1 video call with Homer', 'Personalized conversation', 'Digital recording of the call', 'Signed digital photo']::text[], ARRAY['Must be 18 years or older', 'Stable internet connection required', 'Valid identification for verification']::text[], ARRAY['Calls are scheduled in advance', 'Time zones will be accommodated', 'Recording for personal use only']::text[], 7),
('Video Greeting', 'Receive a personalized video message from Homer for any occasion.', 'video-greeting', 'signed-items', 'Request Pricing', 'https://www.tvinsider.com/wp-content/uploads/2025/07/richard-gere-homer-gere.jpg', 'available', '1–3 minutes (video)', 'Digital delivery', ARRAY['Personalized HD video message', 'Custom message of your choice', 'Digital delivery within 7 days', 'Unlimited replay']::text[], ARRAY['No age restrictions', 'Message must be appropriate and respectful']::text[], ARRAY['Videos are delivered digitally via email', 'Processing time is 5–7 business days', 'Revisions are not available after delivery']::text[], 8);
